os: Visual Studio 2015 CTP  
version: 1.1.0.{build}

configuration:
- Debug
#- Release

environment:
  matrix:
  # - VS_VERSION: 9 2008
  #   VS_PLATFORM: win32
  # - VS_VERSION: 9 2008
  #   VS_PLATFORM: x64
  #- VS_VERSION: 10 2010
  #  VS_PLATFORM: win32
  #- VS_VERSION: 10 2010
  #  VS_PLATFORM: x64
  # - VS_VERSION: 11 2012
  #   VS_PLATFORM: win32
  # - VS_VERSION: 11 2012
  #   VS_PLATFORM: x64
  #- VS_VERSION: 12 2013
  #  VS_PLATFORM: win32
  #- VS_VERSION: 12 2013
  #  VS_PLATFORM: x64
   - VS_VERSION: 14 2015
     VS_PLATFORM: win32
   - VS_VERSION: 14 2015
     VS_PLATFORM: x64
  # - VS_VERSION: 15 2017
  #   VS_PLATFORM: win32
  # - VS_VERSION: 15 2017
  #   VS_PLATFORM: x64
before_build:
- git submodule update --init --recursive
- cmake -H. -Bbuild/vs -G "Visual Studio %VS_VERSION%" -DCMAKE_GENERATOR_PLATFORM=%VS_PLATFORM%

build:
  project: build\vs\%APPVEYOR_PROJECT_NAME%.sln
  parallel: true
  verbosity: minimal

test_script:
# Environment variables https://www.appveyor.com/docs/environment-variables/
- echo %APPVEYOR% - True (true on Ubuntu image) if build runs in AppVeyor environment
- echo %CI% - True (true on Ubuntu image) if build runs in AppVeyor environment
- echo %APPVEYOR_API_URL% - AppVeyor Build Agent API URL
- echo %APPVEYOR_ACCOUNT_NAME% - account name
- echo %APPVEYOR_PROJECT_ID% - AppVeyor unique project ID
- echo %APPVEYOR_PROJECT_NAME% - project name
- echo %APPVEYOR_PROJECT_SLUG% - project slug (as seen in project details URL)
- echo %APPVEYOR_BUILD_FOLDER% - path to clone directory
- echo %APPVEYOR_BUILD_ID% - AppVeyor unique build ID
- echo %APPVEYOR_BUILD_NUMBER% - build number
- echo %APPVEYOR_BUILD_VERSION% - build version
- echo %APPVEYOR_BUILD_WORKER_IMAGE% - current build worker image the build is running on, e.g. Visual Studio 2015 (also can be used as “tweak” environment variable to set build worker image)
- echo %APPVEYOR_PULL_REQUEST_NUMBER% - GitHub Pull Request number
- echo %APPVEYOR_PULL_REQUEST_TITLE% - GitHub Pull Request title
- echo %APPVEYOR_PULL_REQUEST_HEAD_REPO_NAME% - PR source repo (GitHub only)
- echo %APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH% - PR source branch (GitHub only)
- echo %APPVEYOR_PULL_REQUEST_HEAD_COMMIT% - PR source commit ID (SHA) (GitHub only)
- echo %APPVEYOR_JOB_ID% - AppVeyor unique job ID
- echo %APPVEYOR_JOB_NAME% - job name
- echo %APPVEYOR_JOB_NUMBER% - job number, i.g. 1, 2, etc.
- echo %APPVEYOR_REPO_PROVIDER% - github, bitbucket, kiln, vso or gitlab
- echo %APPVEYOR_REPO_SCM% - git or mercurial
- echo %APPVEYOR_REPO_NAME% - repository name in format owner-name/repo-name
- echo %APPVEYOR_REPO_BRANCH% - build branch. For Pull Request commits it is base branch PR is merging into
- echo %APPVEYOR_REPO_TAG% - true if build has started by pushed tag; otherwise false
- echo %APPVEYOR_REPO_TAG_NAME% - contains tag name for builds started by tag; otherwise this variable is undefined
- echo %APPVEYOR_REPO_COMMIT% - commit ID (SHA)
- echo %APPVEYOR_REPO_COMMIT_AUTHOR% - commit author’s name
- echo %APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL% - commit author’s email address
- echo %APPVEYOR_REPO_COMMIT_TIMESTAMP% - commit date/time in ISO 8601 format
- echo %APPVEYOR_REPO_COMMIT_MESSAGE% - commit message
- echo %APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED% - the rest of commit message after line break (if exists)
- echo %APPVEYOR_SCHEDULED_BUILD% - True if the build runs by scheduler
- echo %APPVEYOR_FORCED_BUILD (True or undefined)% - builds started by “New build” button or from the same API
- echo %APPVEYOR_RE_BUILD (True or undefined)% - build started by “Re-build commit/PR” button of from the same API
- echo %PLATFORM% - platform name set on Build tab of project settings (or through platform parameter in appveyor.yml)
- echo %CONFIGURATION% - configuration name set on Build tab of project settings (or through configuration parameter in appveyor.yml)
# Tweak environment variables
- echo %APPVEYOR_ARTIFACT_UPLOAD_TIMEOUT% - artifact upload timeout in seconds. Default is 600 (10 minutes)
- echo %APPVEYOR_FILE_DOWNLOAD_TIMEOUT% - timeout in seconds to download arbirtary files using appveyor DownloadFile command. Default is 300 (5 minutes)
- echo %APPVEYOR_REPOSITORY_SHALLOW_CLONE_TIMEOUT% - timeout in seconds to download repository (GitHub, Bitbucket or VSTS) as zip file (shallow clone). Default is 1800 (30 minutes)
- echo %APPVEYOR_CACHE_ENTRY_UPLOAD_DOWNLOAD_TIMEOUT% - timeout in seconds to download or upload each cache entry. Default is 300 (5 minutes)
- echo %APPVEYOR_CACHE_SKIP_RESTORE% - set to true to disable cache restore
- echo %APPVEYOR_CACHE_SKIP_SAVE% - set to true to disable cache update
- echo %APPVEYOR_WAP_ARTIFACT_NAME% - custom name for WAP artifact (default is the same as project name)
- echo %APPVEYOR_WAP_SKIP_ACLS% - set to true to create WAP package, which will prevent Web Deploy from updating ACLs
- echo %APPVEYOR_BUILD_WORKER_IMAGE% - set build worker image for build to run on. Can be done only at build configuration level, not at build time
- echo %APPVEYOR_SKIP_FINALIZE_ON_EXIT% - if appveyor exit or Exit-AppVeyor build was called, exit build even without Finalize steps (on_success, on_finish scripts and build cache save)
- echo %APPVEYOR_SAVE_CACHE_ON_ERROR% - save build cache on build failure. By default build cache is being saved only during successful build Finalize steps
- echo %APPVEYOR_ACS_DEPLOYMENT_UPGRADE_MODE% - Exposes DeploymentUpgradeMode Enumeration when deploying Azure Cloud Service. Default value is Auto. Set it to Manual or Simultaneous if different behavior is required.

