os: Visual Studio 2015 CTP  
version: 1.1.0.{build}

configuration:
#- Debug
 - Release

environment:
  matrix:
  # - VS_VERSION: 9 2008
  #   VS_PLATFORM: win32
  # - VS_VERSION: 9 2008
  #   VS_PLATFORM: x64
  #- VS_VERSION: 10 2010
  #  VS_PLATFORM: win32
  #- VS_VERSION: 10 2010
  #  VS_PLATFORM: x64
  # - VS_VERSION: 11 2012
  #   VS_PLATFORM: win32
  # - VS_VERSION: 11 2012
  #   VS_PLATFORM: x64
  #- VS_VERSION: 12 2013
  #  VS_PLATFORM: win32
  #- VS_VERSION: 12 2013
  #  VS_PLATFORM: x64
   - VS_VERSION: 14 2015
     VS_PLATFORM: win32
   - VS_VERSION: 14 2015
     VS_PLATFORM: x64
  # - VS_VERSION: 15 2017
  #   VS_PLATFORM: win32
  # - VS_VERSION: 15 2017
  #   VS_PLATFORM: x64
before_build:
- git submodule update --init --recursive
- cmake -H. -Bbuild/vs -G "Visual Studio %VS_VERSION%" -DCMAKE_GENERATOR_PLATFORM=%VS_PLATFORM%

build:
  project: build\vs\%APPVEYOR_PROJECT_NAME%.sln
  parallel: true
  verbosity: minimal

test_script:
# Environment variables https://www.appveyor.com/docs/environment-variables/
- echo %APPVEYOR%
- echo %CI%
- echo %APPVEYOR_API_URL%
- echo %APPVEYOR_ACCOUNT_NAME%
- echo %APPVEYOR_PROJECT_ID%
- echo %APPVEYOR_PROJECT_NAME%
- echo %APPVEYOR_PROJECT_SLUG%
- echo %APPVEYOR_BUILD_FOLDER%
- echo %APPVEYOR_BUILD_ID%
- echo %APPVEYOR_BUILD_NUMBER%
- echo %APPVEYOR_BUILD_VERSION%
- echo %APPVEYOR_BUILD_WORKER_IMAGE%
- echo %APPVEYOR_PULL_REQUEST_NUMBER%
- echo %APPVEYOR_PULL_REQUEST_TITLE%
- echo %APPVEYOR_PULL_REQUEST_HEAD_REPO_NAME%
- echo %APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH%
- echo %APPVEYOR_PULL_REQUEST_HEAD_COMMIT%
- echo %APPVEYOR_JOB_ID%
- echo %APPVEYOR_JOB_NAME%
- echo %APPVEYOR_JOB_NUMBER%
- echo %APPVEYOR_REPO_PROVIDER%
- echo %APPVEYOR_REPO_SCM%
- echo %APPVEYOR_REPO_NAME%
- echo %APPVEYOR_REPO_BRANCH%
- echo %APPVEYOR_REPO_TAG%
- echo %APPVEYOR_REPO_TAG_NAME%
- echo %APPVEYOR_REPO_COMMIT%
- echo %APPVEYOR_REPO_COMMIT_AUTHOR%
- echo %APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL%
- echo %APPVEYOR_REPO_COMMIT_TIMESTAMP%
- echo %APPVEYOR_REPO_COMMIT_MESSAGE%
- echo %APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED%
- echo %APPVEYOR_SCHEDULED_BUILD%
- echo %APPVEYOR_FORCED_BUILD%
- echo %APPVEYOR_RE_BUILD%
- echo %PLATFORM%
- echo %CONFIGURATION%
#Tweak environment variables
- echo %APPVEYOR_ARTIFACT_UPLOAD_TIMEOUT%
- echo %APPVEYOR_FILE_DOWNLOAD_TIMEOUT%
- echo %APPVEYOR_REPOSITORY_SHALLOW_CLONE_TIMEOUT%
- echo %APPVEYOR_CACHE_ENTRY_UPLOAD_DOWNLOAD_TIMEOUT%
- echo %APPVEYOR_CACHE_SKIP_RESTORE%
- echo %APPVEYOR_CACHE_SKIP_SAVE%
- echo %APPVEYOR_WAP_ARTIFACT_NAME%
- echo %APPVEYOR_WAP_SKIP_ACLS%
- echo %APPVEYOR_BUILD_WORKER_IMAGE%
- echo %APPVEYOR_SKIP_FINALIZE_ON_EXIT%
- echo %APPVEYOR_SAVE_CACHE_ON_ERROR%
- echo %APPVEYOR_ACS_DEPLOYMENT_UPGRADE_MODE%


deploy:
  release: "%APPVEYOR_PROJECT_NAME%-v%APPVEYOR_BUILD_VERSION%"
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: "%GITHUB_ACCESS_TOKEN%"
  artifact: bin\%configuration%\*.exe
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: "%APPVEYOR_REPO_COMMIT_MESSAGE%" == "BUILD2"
